name: Sync Repo to GCS

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup CLI
      - uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_email: ${{ secrets.GCS_SA_EMAIL }}
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: your-gcp-project-id

      - name: Sync repository to GCS
        run: |
          gsutil -m rsync -d -r --exclude ".git/**" --exclude ".github/**" . gs://now-news-data-lake/scripts
