name: Sync Repo to GCS

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout del repositorio
      - uses: actions/checkout@v2

      # Autenticaci√≥n con GCP usando la clave JSON del servicio
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCS_SA_KEY }}

      # Configura gcloud con el proyecto
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: your-gcp-project-id

      # Sincroniza solo la carpeta scripts
      - name: Sync scripts to GCS
        run: |
            gsutil -m rsync -d -r -x "(\.git|\.github|gha-creds.*\.json)" . gs://now-news-data-lake/scripts